### PR TITLE
646 fix

### LINKED ISSUE #646: Bug: (V4) dataview-from filter in codeblock has no effect (regression after 4.2.35-beta)
## Describe the bug

The "dataview-from" option in a breadcrumbs codeblock no longer filters the results. Notes from excluded folders/paths continue to appear in the output as if the filter is being ignored entirely. This worked correctly in 4.2.35-beta (last known working beta version).

## To Reproduce

Notes spread across regular folders and excluded folders (e.g. templates/, archives/).
Add the following codeblock:

```breadcrumbs
type: mermaid
fields: [Child]
depth: [0, 3]
sort: basename asc
dataview-from: '!"templates" or !"archives"'
```
Observe that notes inside templates/ and archives/ still appear in the rendered output.

## Expected behavior
Notes matching the dataview-from exclusion query should be filtered out from the mermaid results, as they were in version 4.2.35-beta.

## Version information

Breadcrumbs version: set to 4.2.35-beta with BRAT (last known working version)
Obsidian version: v1.11.7 (stable)
Dataview version: 0.5.68
OS: macOS Tahoe and iOS 26.3

### PR DESCRIPTION
**Pull request by michaelpporter**
fixes #646 
 
This pull request introduces several important updates focused on improving Rust toolchain compatibility, enhancing traversal filtering capabilities, and updating versioning across the codebase. The most significant change is the migration from the Rust nightly toolchain to stable, which affects build scripts and the WASM module. Additionally, traversal logic now supports filtering by allowed target nodes, enabling new features such as the `dataview-from` filter in codeblocks. Version numbers have been incremented to reflect these updates.

**Toolchain and Build System Updates**
* Migrated Rust toolchain from nightly to stable in the GitHub workflow (`.github/workflows/release.yml`), `Makefile`, and `wasm/rust-toolchain`, and updated the edition in `wasm/Cargo.toml` to 2024 for compatibility. [[1]](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L24-R31) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L4-R5) [[3]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L16-R35) [[4]](diffhunk://#diff-e699bbad45488972cc34d8f315c68cf7ca8962aa78c5ba15d4cbb4308eaadb6dL1-R1) [[5]](diffhunk://#diff-d6a02d3c6e0a91077a2fe64bb1c7251fb3bb1df438495b8d0824ffa9ba57802dL5-R5)

**Traversal Filtering Enhancements**
* Added `dataview_from_paths` to `TraversalOptions` and implemented logic in Rust WASM code (`wasm/src/traversal/mod.rs`, `wasm/src/traversal/options.rs`) to restrict traversals to allowed target nodes, supporting new codeblock filtering features. [[1]](diffhunk://#diff-657f69b8e876f4aedd7ed0334b907d3b2df8567d3c17031de97f04d4f4345dcbR26-R29) [[2]](diffhunk://#diff-657f69b8e876f4aedd7ed0334b907d3b2df8567d3c17031de97f04d4f4345dcbR41-R49) [[3]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R40) [[4]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R56-R59) [[5]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R79) [[6]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R90) [[7]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R140) [[8]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113L144-R154) [[9]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R178) [[10]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R199) [[11]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R213) [[12]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R228) [[13]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R249) [[14]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R260) [[15]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R280) [[16]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R291) [[17]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R303) [[18]](diffhunk://#diff-8fd5439643306674a2298a7e5429bcad6121a288e00f4ffe00ed3887ccf68113R326-R331) [[19]](diffhunk://#diff-657f69b8e876f4aedd7ed0334b907d3b2df8567d3c17031de97f04d4f4345dcbL1-R1)

**Frontend and Plugin Integration**
* Updated Svelte components and commands to pass the new `dataview-from-paths` option to traversal logic, enabling filtering in codeblocks and views. [[1]](diffhunk://#diff-349769de090e8004e9433a586d2a6c4b28d3eb2a3eca6b21a42a6fec8d2095c9R141) [[2]](diffhunk://#diff-5547f608040cb030e8a98077a520f479944476566af91e0a7b47c6fad530fe16R65) [[3]](diffhunk://#diff-d74daafdff88032fc1eeb53691d3e7bc200c4a8faa3ba7ecf01b1ff2f5a4f4c6R62) [[4]](diffhunk://#diff-d654742dec3a7382ed9b7f0e0f71cbaac6bb30d21574cd884023aeddedf14788R69) [[5]](diffhunk://#diff-6aab8943507e6d2e912eddfd8de5897ca0c3b1098dfb8f8f4e51273a0d3dd0a4R51) [[6]](diffhunk://#diff-6e47714f78c5fc6a815d75493f120a44cb2629d694840489d7efe08b1ad35c30R62) [[7]](diffhunk://#diff-6e47714f78c5fc6a815d75493f120a44cb2629d694840489d7efe08b1ad35c30R74) [[8]](diffhunk://#diff-f45228b68580a4833b2ddd828a79e663e029547bb638df7bb25501dad3a74e7eL92-R92)

**Version Bumps**
* Incremented plugin and package versions to `4.4.1-beta` in `manifest-beta.json`, `package.json`, and `versions.json` to reflect new features and compatibility changes. [[1]](diffhunk://#diff-5d1ea7e89f10bd1845c512a02c3bda22802705dcaeef31d0361a7d2a773c5befL4-R4) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[3]](diffhunk://#diff-2b39d33506bc7a34cef4b9ebf4cf8b1e3a5532f2131ceb37011b94261cec5f8cL249-R250)

**Bug Fixes and Minor Improvements**
* Fixed logic in `BreadcrumbsPlugin` and settings migration, and made minor code cleanups. [[1]](diffhunk://#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dL315-R315) [[2]](diffhunk://#diff-593c9c0ad24b21ce4106d0b023fe70ee8f8ade5a4dac66738bbac179e593c3e5L167-R167) [[3]](diffhunk://#diff-901b937788fb197ba60095e77dd009929e99c885975c72c2a419753580ee1b0cR14) [[4]](diffhunk://#diff-5547f608040cb030e8a98077a520f479944476566af91e0a7b47c6fad530fe16L77)

Let me know if you want a deeper walkthrough of the traversal filtering or the toolchain migration!

### CODE REVIEW

File: wasm/src/traversal/mod.rs [hunk 1]
```diff
@@ -141,7 +151,11 @@ impl NoteGraph {
                 if edge_matches_edge_filter(edge_data, edge_types) {
                     let target = outgoing_edge.target();
 
-                    // assert!(*self.int_get_node_weight(node).unwrap() == edge.target);
+                    if let Some(ref allowed) = allowed_targets {
```
Comment (mProjectsCode) [inline wasm/src/traversal/mod.rs]: you can collapse the two nested if statements with an and `&&`.

File: wasm/src/traversal/mod.rs [hunk 2]
```diff
@@ -52,6 +53,12 @@ impl NoteGraph {
 
                 let target = edge.target();
 
+                if let Some(ref allowed) = allowed_targets {
```
Comment (mProjectsCode) [inline wasm/src/traversal/mod.rs]: Same thing here about collapsing the if statements into one.

**Comment by mProjectsCode** [comment]
Looks good, some small nits about code style regarding if let chains [(possible since Rust 1.88)](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/#let-chains).

**Comment by mProjectsCode** [comment]
I probably need to look at the Rust code and see if we can switch to stable from nightly now. Not sure anymore why I used the nightly compiler in the first place.

**Comment by michaelpporter** [comment]
@mProjectsCode updated rust from 2021 to 2024 and stable. updated the if's based on input.

Had to update rust to 2024...`let chains are only allowed in Rust 2024 or laterrumbs_graph_wasm`

**Comment by michaelpporter** [comment]
@mProjectsCode thank you for your time looking at this.

**Review by SkepticMystic — DISMISSED** [review]
Thank you, guys!
Just two small changes to the readme, but approved

**Review by SkepticMystic — APPROVED** [review]
